# Generated by Django 5.1 on 2026-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shopkeeperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperprofile',
            name='is_manually_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopkeeperprofile',
            name='plan',
            field=models.CharField(choices=[('free_trial', 'Free Trial (7 days)'), ('monthly', 'Monthly (₹399/month)'), ('yearly', 'Yearly (₹4999/year)'), ('blocked', 'Blocked')], default='free_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='shopkeeperprofile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopkeeperprofile',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
