# Generated by Django 5.1 on 2026-04-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_shopkeeperprofile_is_manually_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeperprofile',
            name='plan',
            field=models.CharField(choices=[('free_trial', 'Free Trial (7 days)'), ('monthly', 'Monthly (₹99/month)'), ('yearly', 'Yearly (₹999/year)'), ('blocked', 'Blocked')], default='free_trial', max_length=20),
        ),
    ]
